name: fantasy_ui_example
description: Demonstrates how to use the fantasy_ui package
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '^3.7.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fantasy_ui:
    path: ../
  flutter_colorpicker: ^1.1.0
flutter:
  uses-material-design: true
